project:
  type: website

website:
  title: "Ben Dahmen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: cv.qmd
        text: CV
    #foreground: "#393D3E"
    #background: "#ECECEC"
    search: false
format:
  html:
    theme:
      - default
      - custom.scss
    css: styles.css
    toc: true

editor: visual

